--cleaned fact_internetsales table --
SELECT  [ProductKey]
      ,[OrderDateKey]
      ,[DueDateKey]
      ,[ShipDateKey]
      ,[CustomerKey]
      --,[PromotionKey]
      --,[CurrencyKey]
      --,[SalesTerritoryKey]
      ,[SalesOrderNumber]
      --,[SalesOrderLineNumber]
      --,[RevisionNumber]
      --,[OrderQuantity]
      --,[UnitPrice]
      --,[ExtendedAmount]
      --,[UnitPriceDiscountPct]
      --,[DiscountAmount]
     -- ,[ProductStandardCost]
     -- ,[TotalProductCost]
      ,[SalesAmount]
      --,[TaxAmt]
     -- ,[Freight]
     -- ,[CarrierTrackingNumber]
     -- -,[CustomerPONumber]
     -- ,[OrderDate]
     -- ,[DueDate]
      --,[ShipDate]
  FROM [dbo].[FactInternetSales]
  where
  left (OrderDateKey, 5) >= YEAR(GETDATE()) -2 --THIS YEAR(GETDATE()) can update automatically our date and dont need manually change
  ORDER BY 
  OrderDateKey ASC